import type { Application, Stage, StageId } from "./types";

export const stageOrder: StageId[] = [
  "applied",
  "hr_response",
  "screening",
  "tech",
  "homework",
  "final",
  "offer",
  "rejected",
];

export const stagesByLanguage: Record<"ru" | "en", Stage[]> = {
  ru: [
    { id: "applied", title: "Отклик" },
    { id: "hr_response", title: "Ответ HR" },
    { id: "screening", title: "Скрининг" },
    { id: "tech", title: "Тех интервью" },
    { id: "homework", title: "Тестовое" },
    { id: "final", title: "Финал" },
    { id: "offer", title: "Оффер" },
    { id: "rejected", title: "Отказ" },
  ],
  en: [
    { id: "applied", title: "Applied" },
    { id: "hr_response", title: "HR Response" },
    { id: "screening", title: "Screening" },
    { id: "tech", title: "Tech Interview" },
    { id: "homework", title: "Homework" },
    { id: "final", title: "Final" },
    { id: "offer", title: "Offer" },
    { id: "rejected", title: "Rejected" },
  ],
};

export const sampleApplications: Application[] = [
  {
    id: "app-001",
    company: "Pixel&Co",
    role: "Product Designer",
    location: "Remote, EU",
    salary: "€3,500-4,200",
    notes: "Проверить кейсы, подготовить portfolio walkthrough.",
    stage: "screening",
    appliedAt: "2026-01-27",
    lastTouch: "2026-02-10",
    priority: "high",
    source: "Referral",
  },
  {
    id: "app-002",
    company: "Nova Systems",
    role: "Frontend Engineer",
    location: "Berlin",
    salary: "€75k-90k",
    notes: "Ожидают второй раунд, уточнить stack и формат теста.",
    stage: "tech",
    appliedAt: "2026-01-30",
    lastTouch: "2026-02-13",
    priority: "high",
    source: "LinkedIn",
  },
  {
    id: "app-003",
    company: "Cloud Harbor",
    role: "Solutions Architect",
    location: "Remote, US",
    salary: "$140k-165k",
    notes: "Отправить follow-up после ответа HR.",
    stage: "hr_response",
    appliedAt: "2026-02-03",
    lastTouch: "2026-02-08",
    priority: "medium",
    source: "Company site",
  },
  {
    id: "app-004",
    company: "Kindred Labs",
    role: "Data Analyst",
    location: "London",
    salary: "£55k-65k",
    notes: "Сделать заметку про интерес к гибриду.",
    stage: "applied",
    appliedAt: "2026-02-11",
    lastTouch: "2026-02-11",
    priority: "low",
    source: "Inbound",
  },
  {
    id: "app-005",
    company: "Atlas Motion",
    role: "Product Manager",
    location: "New York",
    salary: "$120k-140k",
    notes: "Подготовить список вопросов про команду и KPI.",
    stage: "final",
    appliedAt: "2026-01-21",
    lastTouch: "2026-02-14",
    priority: "high",
    source: "Recruiter",
  },
  {
    id: "app-006",
    company: "Blue Orchard",
    role: "QA Lead",
    location: "Remote, US",
    salary: "$95k-110k",
    notes: "Ожидаем оффер-детали, запросить бенефиты.",
    stage: "offer",
    appliedAt: "2025-12-19",
    lastTouch: "2026-02-02",
    priority: "medium",
    source: "Referral",
  },
  {
    id: "app-007",
    company: "Quantum Stack",
    role: "Backend Engineer",
    location: "Prague",
    salary: "€60k-75k",
    notes: "Дедлайн на тестовое 3 дня.",
    stage: "homework",
    appliedAt: "2026-01-29",
    lastTouch: "2026-02-12",
    priority: "medium",
    source: "Meetup",
  },
  {
    id: "app-008",
    company: "Studio 47",
    role: "UX Researcher",
    location: "Remote, UK",
    salary: "£50k-60k",
    notes: "Запросить фидбек по причине отказа.",
    stage: "rejected",
    appliedAt: "2025-12-10",
    lastTouch: "2026-01-05",
    priority: "low",
    source: "Referral",
  }
];
